name: Build GoWebDAV

on:
  repository_dispatch:
    types: [x86_64, x86]
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *
#  watch:
#    types: started
    
env:
  UPLOAD_HUB_DOCKER: true
  UPLOAD_Ali_SH: true
  UPLOAD_Ali_SZ: true
  IMAGE-NAME: golang-webdav
  IMAGE-VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Docker Build
        id: build
        run: |
          sudo docker build -t ${{ env.IMAGE-NAME }}:${{ env.IMAGE-VERSION }} .
          echo "IMAGE=$PWD" >> $GITHUB_ENV
          echo "::set-output name=status::success"
        
      - name: Docker Build and Push Docker Hub
        if: steps.build.outputs.status == 'success' && env.UPLOAD_HUB_DOCKER == 'true' && !cancelled()
        run: |
          cd $IMAGE
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PWD }}
          sudo docker push ${{ env.IMAGE-NAME }}:${{ env.IMAGE-VERSION }}
        
      - name: Push Docker Image To Aliyun Shanghai Registry
        if: steps.build.outputs.status == 'success' && env.UPLOAD_Ali_SH == 'true' && !cancelled()
        run: |
          cd $IMAGE
          docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PWD }} registry.cn-shanghai.aliyuncs.com
          sudo docker tag ${{ env.IMAGE-NAME }}:${{ env.IMAGE-VERSION }} registry.cn-shanghai.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/${{ env.IMAGE-NAME }}:${{ env.IMAGE-VERSION }}
          sudo docker push registry.cn-shanghai.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/${{ env.IMAGE-NAME }}:${{ env.IMAGE-VERSION }}
