name: Build GoWebDAV

on:
  repository_dispatch:
    types: [x86_64, x86]
  workflow_dispatch:
#  schedule:
#    - cron: 0 16 * * *
  watch:
    types: started
    
env:
  UPLOAD_HUB_DOCKER: true
  UPLOAD_Ali_SH: true
  UPLOAD_Ali_SZ: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [gowebdav]
        image-version: [latest]

    steps:
    - name: Checkout
    - uses: actions/checkout@main
      
    - name: Docker Build
      id: build
      run: |
        docker build -t ${{ matrix.image-name }}:${{ matrix.image-version }} .
        
    - name: Docker Build and Push Docker Hub
      if: steps.organized.outputs.status == 'success' && env.UPLOAD_HUB_DOCKER == 'true' && !cancelled()
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PWD }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image-name }}:${{ matrix.image-version }}
        
    - name: Push Docker Image To Aliyun Shanghai Registry
      if: steps.organized.outputs.status == 'success' && env.UPLOAD_Ali_SH == 'true' && !cancelled()
      run: |
        docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PWD }} registry.cn-shanghai.aliyuncs.com
        docker tag ${{ matrix.image-name }}:${{ matrix.image-version }} registry.cn-shanghai.aliyuncs.com/onceace/${{ matrix.image-name }}:${{ matrix.image-version }}
        docker push registry.cn-beijing.aliyuncs.com/onceace/${{ matrix.image-name }}:${{ matrix.image-version }}
