name: Build GoWebDAV

on:
#  repository_dispatch:
#    types: [x86_64, x86]
  workflow_dispatch:
#  schedule:
#    - cron: 0 * 1 * *
#  watch:
#    types: started
    
env:
  UPLOAD_HUB_DOCKER: true
  UPLOAD_Ali_SH: true
  UPLOAD_Ali_SZ: true
  IMAGE-NAME: golang-webdav
  IMAGE-VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Build
        id: build
        run: |
          sudo run main.go
